name: Build and Push Docker Image

on:
  push:
    branches:
      - '*'

jobs:
  build-base:
    runs-on: ubuntu-latest

    steps:
    - id: lowercaseRepo
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ github.repository }}
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create short sha and tag
      shell: bash
      run: |
        echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
        if [[ "$GITHUB_REF" == "refs/heads/master" ]]; then echo TAG=latest; else echo TAG="${GITHUB_REF##*/}"; fi >> $GITHUB_ENV
    - name: Build Base Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        file: docker/Dockerfile.kaldi-vosk-server-gpu
        tags: |
          ghcr.io/${{ steps.lowercaseRepo.outputs.lowercase }}:base-server-gpu-${{ env.SHORT_SHA }}
          ghcr.io/${{ steps.lowercaseRepo.outputs.lowercase }}:base-server-gpu-${{ env.TAG }}
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        file: docker/Dockerfile.kaldi-ru-gpu
        build-args: BASE_IMAGE=ghcr.io/${{ steps.lowercaseRepo.outputs.lowercase }}:base-server-gpu-${{ env.TAG }}
        tags: |
          ghcr.io/${{ steps.lowercaseRepo.outputs.lowercase }}:kaldi-ru-gpu-${{ env.SHORT_SHA }}
          ghcr.io/${{ steps.lowercaseRepo.outputs.lowercase }}:kaldi-ru-gpu-${{ env.TAG }}
          ghcr.io/${{ steps.lowercaseRepo.outputs.lowercase }}:${{ env.TAG }}
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max
